# Generated by Django 5.2.8 on 2025-11-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_order_orderitem_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stripe_tax_rate_id', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='myapi.tax'),
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='myapi.tax'),
        ),
    ]
