# Generated by Django 5.2.8 on 2025-11-20 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_remove_order_taxes_order_taxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='taxes',
        ),
        migrations.AddField(
            model_name='item',
            name='taxes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.tax'),
        ),
    ]
