# Generated by Django 5.2.8 on 2025-11-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_remove_item_taxes_item_taxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coupon_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='taxes',
            new_name='tax',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='taxes',
            new_name='tax',
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.discount'),
        ),
    ]
