# Generated by Django 5.2.8 on 2025-11-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_item_discount_alter_item_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('rub', 'RUB')], default='usd', max_length=3),
        ),
    ]
